# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'



target 'runlines' do
  pod 'Firebase/Core'	
  pod 'Firebase/Firestore'	
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for runlines

  # target 'runlines-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end


  # target 'runlinesTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

# end

# target 'runlines-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for runlines-tvOS

  # target 'runlines-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
