# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'runlines' do
  pod 'Firebase/Core'	
  pod 'Firebase/Firestore'	
  pod 'React', :path => '../node_modules/react-native'
# , :subspecs => [
#     'Core',
#     'CxxBridge', # Include this for RN >= 0.47
#     'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
#     'RCTText',
#     'RCTNetwork',
#     'RCTWebSocket', # Needed for debugging
#     'RCTAnimation', # Needed for FlatList and animations running on native UI thread
#     # Add any other subspecs you want to use in your project
#   ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'





  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'runlinesTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

# end

# target 'runlines-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for runlines-tvOS

  # target 'runlines-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

#    post_install do |installer_representation|
#      installer_representation.pods_project.targets.each do |target|
#          if target.name == "React"
#              target.remove_from_project
#          end
#      end
#  end
